apiVersion: v2
name: istio
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: base
    version: "1.17.1"
    repository: "https://istio-release.storage.googleapis.com/charts"
    condition: istio_base.enabled
  - name: istiod
    version: "1.17.1"
    repository: "https://istio-release.storage.googleapis.com/charts"
    condition: istio.enabled
